### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by itsdfish** [itsdfish/JokerJailBreak.jl#1]
@JuliaRegistrator register()

**Comment by Rratic** [comment]
Wait, I guess this is only an implemention of a game, so why is it required to be registered?

**Comment by itsdfish** [comment]
I don't think registration is a requirement per se. Am I in violation of a registration policy?

**Comment by Rratic** [comment]
> Am I in violation of a registration policy?

Here's a quote from https://github.com/JuliaRegistries/General#should-i-register-my-package-now
> The General registry is not a place for "personal packages" that consist of collections of "utility functions" nor for packages that are only useful for a closed group (like a research group or a company). For that, it is easy to set up your own registry using for example [LocalRegistry.jl](https://github.com/GunnarFarneback/LocalRegistry.jl). The [Pkg documentation about registries](https://pkgdocs.julialang.org/v1/registries/) might be useful if you decide to go this route.

I guess this is a "personal package", at least from my understanding of your purpose. By the way, if you do not choose to register the package in `General`, you can have more things that are up to you.

**Comment by itsdfish** [comment]
I am still confused about the policy because the term "personal use" is not defined, which makes it impossible to know if I am in violation of the policy.

I recommend opening an issue in the general registry and proposing clearer criteria on what constitutes personal use and perhaps a method for enforcing the policy.  For example, a package must satisfy 3 out of 4 criteria to be registered. If the package does not meet the guidelines, an individual can submit an issue on the general  registry with an explanation detailing how the package fails the guidelines.

**Comment by Rratic** [comment]
Well, I can't decide on this. It's ok to register if you want since it's not so influential, only that it's a little akward. I guess *we* can open an issue.

**Comment by itsdfish** [comment]
Thanks for opening an issue with the general registry. I think having clearer guidelines will be useful for the community.
